In [4]:
import pandas as pd

df = pd.read_csv("US_flights_2023.csv")

print(df.shape)
print(df.columns.tolist())

(6743404, 24)
['FlightDate', 'Day_Of_Week', 'Airline', 'Tail_Number', 'Dep_Airport', 'Dep_CityName', 'DepTime_label', 'Dep_Delay', 'Dep_Delay_Tag', 'Dep_Delay_Type', 'Arr_Airport', 'Arr_CityName', 'Arr_Delay', 'Arr_Delay_Type', 'Flight_Duration', 'Distance_type', 'Delay_Carrier', 'Delay_Weather', 'Delay_NAS', 'Delay_Security', 'Delay_LastAircraft', 'Manufacturer', 'Model', 'Aicraft_age']

In [5]:
atl = df[(df["Dep_Airport"] == "ATL") | (df["Arr_Airport"] == "ATL")].copy()

print("All US flights:", len(df))
print("ATL flights:",len(atl))
atl.head()

All US flights: 6743404
ATL flights: 665876

,FlightDate,Day_Of_Week,Airline,Tail_Number,Dep_Airport,Dep_CityName,DepTime_label,Dep_Delay,Dep_Delay_Tag,Dep_Delay_Type,...,Flight_Duration,Distance_type,Delay_Carrier,Delay_Weather,Delay_NAS,Delay_Security,Delay_LastAircraft,Manufacturer,Model,Aicraft_age
31,2023-01-09,1,Endeavor Air,N181GJ,ATL,"Atlanta, GA",Afternoon,-3,0,Low <5min,...,67,Short Haul >1500Mi,0,0,0,0,0,CANADAIR REGIONAL JET,CRJ,16
32,2023-01-10,2,Endeavor Air,N937XJ,ATL,"Atlanta, GA",Afternoon,-5,0,Low <5min,...,69,Short Haul >1500Mi,0,0,0,0,0,CANADAIR REGIONAL JET,CRJ,16
33,2023-01-11,3,Endeavor Air,N604LR,ATL,"Atlanta, GA",Afternoon,-2,0,Low <5min,...,71,Short Haul >1500Mi,0,0,0,0,0,CANADAIR REGIONAL JET,CRJ,16
34,2023-01-12,4,Endeavor Air,N371CA,ATL,"Atlanta, GA",Afternoon,16,1,Medium >15min,...,71,Short Haul >1500Mi,0,0,0,0,0,CANADAIR REGIONAL JET,CRJ,21
35,2023-01-13,5,Endeavor Air,N324PQ,ATL,"Atlanta, GA",Afternoon,-3,0,Low <5min,...,71,Short Haul >1500Mi,0,0,0,0,0,CANADAIR REGIONAL JET,CRJ,10

In [6]:
atl.info()

<class 'pandas.DataFrame'>
Index: 665876 entries, 31 to 6743327
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   FlightDate          665876 non-null  str
 1   Day_Of_Week         665876 non-null  int64
 2   Airline             665876 non-null  str
 3   Tail_Number         665876 non-null  str
 4   Dep_Airport         665876 non-null  str
 5   Dep_CityName        665876 non-null  str
 6   DepTime_label       665876 non-null  str
 7   Dep_Delay           665876 non-null  int64
 8   Dep_Delay_Tag       665876 non-null  int64
 9   Dep_Delay_Type      665876 non-null  str
 10  Arr_Airport         665876 non-null  str
 11  Arr_CityName        665876 non-null  str
 12  Arr_Delay           665876 non-null  int64
 13  Arr_Delay_Type      665876 non-null  str
 14  Flight_Duration     665876 non-null  int64
 15  Distance_type       665876 non-null  str
 16  Delay_Carrier       665876 non-null  int64
 17  Delay_Weather       665876 non-null  int64
 18  Delay_NAS           665876 non-null  int64
 19  Delay_Security      665876 non-null  int64
 20  Delay_LastAircraft  665876 non-null  int64
 21  Manufacturer        665876 non-null  str
 22  Model               665876 non-null  str
 23  Aicraft_age         665876 non-null  int64
dtypes: int64(11), str(13)
memory usage: 205.8 MB

In [8]:
atl.to_csv("atl_flights_2023.csv", index = False)

In [15]:
atl["FlightDate"] = pd.to_datetime(atl["FlightDate"])
atl["Month"] = atl["FlightDate"].dt.month
atl["Month_Name"] = atl["FlightDate"].dt.month_name()
atl = atl.rename(columns={"Aicraft_age": "Aircraft_Age"})
atl = atl.reset_index(drop=True)
atl[["FlightDate", "Month", "Month_Name", "Aircraft_Age"]].head()

  FlightDate  Month Month_Name  Aircraft_Age
0 2023-01-09      1    January            16
1 2023-01-10      1    January            16
2 2023-01-11      1    January            16
3 2023-01-12      1    January            21
4 2023-01-13      1    January            10

In [16]:
atl[["Dep_Delay", "Arr_Delay", "Delay_Carrier", "Delay_Weather",
"Delay_NAS", "Delay_Security", "Delay_LastAircraft", "Aircraft_Age"]].describe()

,Dep_Delay,Arr_Delay,Delay_Carrier,Delay_Weather,Delay_NAS,Delay_Security,Delay_LastAircraft,Aircraft_Age
count,665876.000000,665876.000000,665876.000000,665876.000000,665876.000000,665876.000000,665876.000000,665876.000000
mean,11.266344,4.785995,5.518077,0.709725,2.093675,0.020974,3.991296,15.692243
std,48.685934,50.733669,35.495704,13.402604,13.066335,1.247031,23.138789,8.928778
min,-39.000000,-70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,-4.000000,-15.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000
50%,-1.000000,-7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,16.000000
75%,8.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.000000
max,3221.000000,3237.000000,3221.000000,1197.000000,1300.000000,323.000000,2216.000000,57.000000

In [17]:
atl["Arr_Delay_Tag"] = (atl["Arr_Delay"] >= 15).astype(int)

print("% departures delayed 15+ min:", round(atl["Dep_Delay_Tag"].mean() * 100, 1))
print("% arrivals delayed 15+ min:", round(atl["Arr_Delay_Tag"].mean() * 100, 1))
print("Departures delayed 3+ hours:", (atl["Dep_Delay"] >= 180).sum())

% departures delayed 15+ min: 37.1
% arrivals delayed 15+ min: 18.1
Departures delayed 3+ hours: 7733

In [18]:
atl["Dep_Delay_15"] = (atl["Dep_Delay"] >= 15).astype(int)

print("% departures delayed 15+ min:", round(atl["Dep_Delay_15"].mean() * 100, 1))
print("Smallest delay tagged by the dataset:", atl.loc[atl["Dep_Delay_Tag"] == 1, "Dep_Delay"].min())

% departures delayed 15+ min: 19.1
Smallest delay tagged by the dataset: 1

In [19]:
atl = atl.drop(columns=["Dep_Delay_Tag"])

atl.to_csv("atl_flights_2023_clean.csv", index=False)

print(atl.shape)

(665876, 27)